### ISSUE TITLE
Add Japanese documentation

### ISSUE THREAD

**Issue by Shugyousha** [pond3r/ggpo#2]
There is no Japanese documentation yet which would be good to have.

I would like to start the translation of the current documentation into Japanese.

Should we add a subdirectory in the doc/ folder (i. e. doc/ja/) or just add a suffix to the markdown documents (i. e. DevelopmentGuide.ja.md)?

**Comment by JakeTheJake74** [comment]
I had someone professionally translate the site and some of the files!
https://docs.google.com/spreadsheets/d/1IA07PBIBIS-CEak2Vf0UoZhej28C0cT8Rh4Cq8B7Rq0/htmlview
Do what you can with these.

**Comment by Shugyousha** [comment]
JakeTheJake74 <notifications@github.com> wrote:
> I had someone professionally translate the site and some of the files!
> https://docs.google.com/spreadsheets/d/1IA07PBIBIS-CEak2Vf0UoZhej28C0cT8Rh4Cq8B7Rq0/htmlview
> Do what you can with these.

These will save me a lot of time, thanks!

I will use the developer guide translation and cross-check the parts I
have done already.

**Comment by JakeTheJake74** [comment]
No problem! Glad that helped. The guy who I hired to do it was great.
To answer your question in the O.P. btw. I think a sub doc would probably be best. Maybe have it also be in Japanese so it’s as obvious as possible which one they should click.
doc/english, doc/日本語

**Comment by Shugyousha** [comment]
JakeTheJake74 <notifications@github.com> wrote:
> No problem! Glad that helped. The guy who I hired to do it was great.

That was really useful and very generous. I still have to go through my
translation but I will open a new PR for that.

You can find the PR for the developer guide here:

https://github.com/pond3r/ggpo/pull/34

 
> To answer your question in the O.P. btw. I think a sub doc would
> probably be best. Maybe have it also be in Japanese so it’s as
> obvious as possible which one they should click.
> doc/english, doc/日本語

I am hesitant to put a non-ascii directory name there for technical
reasons. Instead just using the 2 letter language ISO code of 'ja'
should be understandable.

I will open a new PR for the documentation directory structure change
once all the translations have been finished.

**Comment by Shugyousha** [comment]
I have opened a PR to add a translation of the README.md at the root of the repo and to correct my own translation: https://github.com/pond3r/ggpo/pull/35

**Comment by seasidelab** [comment]
Another update was merged while correcting the Japanese document, so it was readjusted based on the latest commit.

**Comment by Shugyousha** [comment]
With these changes merged, the translation should now be complete.

Now the only question remaining is if we want to keep the current '*ja.md' files or if we want to create a subdirectory in doc/, i. e. `doc/en` and `doc/ja` (or `doc/日本語` but I would be against this). Would be good to have some input from pond3r there.

**Comment by pond3r** [comment]
I think I'd prefer to keep the current naming, but maybe add a blob of japanese to the top of the README.md that links to the README.ja.md.  How does that sound?

**Comment by JakeTheJake74** [comment]
That sounds close to perfect.

**Comment by Shugyousha** [comment]
> I think I'd prefer to keep the current naming, but maybe add a blob of japanese to the top of the README.md that links to the README.ja.md. How does that sound?

Perfect. The PR is here https://github.com/pond3r/ggpo/pull/44

**Comment by Shugyousha** [comment]
Since the last addition has been merged already, this issue can now be closed.
