### ISSUE TITLE
Is there a maximum size in bytes for an input when creating a GGPOSession? 

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [pond3r/ggpo#54]
So I've been testing GGPO on Linux, which I know isn't a supported plaform yet, and I've run into a small problem. I've noticed that GGPO crashes when the input size is anything larger than 18 bytes. Is 18 bytes the maximum input size that GGPO supports? Or is this simply a bug? I'm using a branch based on PR #52 .

**Comment by Shugyousha** [comment]
It looks like 18 bytes is the preconfigured max: https://github.com/pond3r/ggpo/blob/master/src/lib/ggpo/game_input.h#L26

I assume that can be adjusted freely (as long as you make sure to heed this comment: https://github.com/pond3r/ggpo/blob/master/src/lib/ggpo/game_input.h#L14).

**Comment by pond3r** [comment]
Yes, you should be fine, though I've never tested it with inputs that large.

**Comment by Eoin-ONeill-Yokai** [comment]
Ok that's good to know. 

I'm going to go ahead and close this issue then since it seems to be addressed. Thanks for taking the time to respond!
