### ISSUE TITLE
Quick Question about missing bin file in build.

### ISSUE THREAD

**Issue by UmaiRamen** [pond3r/ggpo#63]
so I build ggpo using cmake with it shared path with all, (middle option during installation)

but it lacks the build bin while which has the ggpo.dll and ggpo.pdb file, how do I make it so that I can have these files.
![explorer_l8tAPTBkSy](https://user-images.githubusercontent.com/34729683/123228505-54e80800-d48a-11eb-8322-6440719a181e.png)

**Comment by Tngsten** [comment]
bro, how did you solve it? im facing the same problem.. i might be dumb
